apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp1
    type: frontend
  name: pod4
spec:
  containers:
          - image: coolgourav147/nginx-custom
            imagePullPolicy: Never
            name: myapp-container
            resources: 
                requests:
                        memory: 1Mi
                        cpu: 0.1
                limits:
                        memory: 200Mi

