apiVersion: v1

kind: ReplicationController

metadata:
        name: fistreplicationcontroler
        labels:
                appname: voatingapp
spec:
        replicas: 8
        template:
                metadata:
                        name: fristpod1
                        labels:
                         type: app
                spec:
                        containers:
                          - image: coolgourav147/nginx-custom
                            name: secondpodd


